version: "3"
services:
    db:
        image: mysql:latest
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mysql
            MYSQL_USER: rpf511
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - "./data:/var/lib/mysql:rw"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        ports:
            - 8084:80
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: rpf511
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
    web:
        build:
          context: .
          dockerfile: ./Dockerfile
        container_name: webprac
        ports: 
            - "80:80"
        volumes:
            - "./www/html/:/var/www/html/"
        depends_on:
            - db
        networks:
            - default
        stdin_open: true
        tty: true
volumes:
    persistent:
